name: Bug report
description: Something is broken
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What went wrong? Be specific.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. v0.6.0

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 120, Safari 17

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. macOS 14.2, Windows 11

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, logs, error messages...
