#!/usr/bin/env node

/* ═══════════════════════════════════════════════════════════════
   MEMORY-INDEX — auto-generate .claude/memory/INDEX.md

   Scans all memory entries, parses YAML frontmatter, produces a
   structured sommaire by type with tag counts and status highlights.

   Usage:
     pnpm memory:index           → regenerate INDEX.md
     node scripts/memory-index.js
   ═══════════════════════════════════════════════════════════════ */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

import { PATHS } from './utils/paths.js';

const MEMORY_DIR = join(PATHS.root, '.claude/memory');
const INDEX_PATH = join(MEMORY_DIR, 'INDEX.md');
const TAGS_PATH = join(MEMORY_DIR, 'TAGS.md');
const TYPES = ['decisions', 'feedback', 'patterns', 'frictions', 'sessions'];

// Parse canonical tag vocabulary from TAGS.md
function loadCanonicalTags() {
  const content = readFileSync(TAGS_PATH, 'utf-8');
  const matches = content.match(/`#[a-z0-9-]+`/g) || [];
  return new Set(matches.map((t) => t.replace(/`/g, '')));
}

// Simple YAML frontmatter parser (handles our fixed schema)
function parseFrontmatter(md) {
  const match = md.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const fm = {};
  for (const line of match[1].split('\n')) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, raw] = kv;
    if (raw.startsWith('[')) {
      fm[key] = raw
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
    } else {
      fm[key] = raw.trim();
    }
  }
  return fm;
}

function walk(dir) {
  const entries = [];
  let items;
  try {
    items = readdirSync(dir);
  } catch {
    return entries;
  }
  for (const name of items) {
    if (name.startsWith('.')) continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) continue;
    if (!name.endsWith('.md')) continue;
    const raw = readFileSync(full, 'utf-8');
    const fm = parseFrontmatter(raw);
    if (!fm) continue;
    const titleMatch = raw.slice(raw.indexOf('---', 3) + 3).match(/^\s*#\s+(.+)$/m);
    entries.push({
      path: relative(MEMORY_DIR, full).replace(/\\/g, '/'),
      title: titleMatch ? titleMatch[1].trim() : name.replace('.md', ''),
      ...fm,
    });
  }
  return entries;
}

function main() {
  const canonical = loadCanonicalTags();
  const all = [];
  const unknownTags = new Map();

  for (const folder of TYPES) {
    const typeDir = join(MEMORY_DIR, folder);
    const entries = walk(typeDir);
    entries.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
    for (const e of entries) {
      all.push({ ...e, folder });
      for (const tag of e.tags || []) {
        if (!canonical.has(tag)) {
          unknownTags.set(tag, (unknownTags.get(tag) || 0) + 1);
        }
      }
    }
  }

  // Tag counts across all entries
  const tagCount = {};
  for (const e of all) {
    for (const tag of e.tags || []) {
      tagCount[tag] = (tagCount[tag] || 0) + 1;
    }
  }
  const sortedTags = Object.entries(tagCount).sort((a, b) => b[1] - a[1]);

  const now = new Date().toISOString().slice(0, 10);
  const lines = [];
  lines.push('# Memory Index');
  lines.push('');
  lines.push(`> Auto-generated by \`pnpm memory:index\` on ${now}. Do not edit by hand.`);
  lines.push('');
  lines.push(`**${all.length}** entries · **${sortedTags.length}** distinct tags`);
  lines.push('');

  if (unknownTags.size > 0) {
    lines.push('## ⚠ Unknown tags detected');
    lines.push('');
    lines.push('The following tags are not in `TAGS.md` canonical vocabulary:');
    lines.push('');
    for (const [tag, count] of unknownTags) {
      lines.push(`- \`${tag}\` (${count} occurrences)`);
    }
    lines.push('');
    lines.push('Either fix the entry or add the tag to `TAGS.md` via a decision.');
    lines.push('');
  }

  for (const folder of TYPES) {
    const entries = all.filter((e) => e.folder === folder);
    if (entries.length === 0) continue;
    lines.push(`## ${folder.charAt(0).toUpperCase() + folder.slice(1)}`);
    lines.push('');
    const active = entries.filter((e) => e.status !== 'deprecated' && e.status !== 'superseded');
    const archived = entries.filter((e) => e.status === 'deprecated' || e.status === 'superseded');
    for (const e of active) {
      const tags = (e.tags || []).join(' ');
      lines.push(`- **${e.date || '—'}** — [${e.title}](${e.path}) · ${tags}`);
    }
    if (archived.length > 0) {
      lines.push('');
      lines.push('<details><summary>Archived</summary>');
      lines.push('');
      for (const e of archived) {
        const tags = (e.tags || []).join(' ');
        lines.push(`- ~~**${e.date || '—'}** — [${e.title}](${e.path}) · ${e.status} · ${tags}~~`);
      }
      lines.push('');
      lines.push('</details>');
    }
    lines.push('');
  }

  lines.push('## Tag frequency');
  lines.push('');
  lines.push('| Tag | Count |');
  lines.push('|---|---|');
  for (const [tag, count] of sortedTags) {
    lines.push(`| \`${tag}\` | ${count} |`);
  }
  lines.push('');

  writeFileSync(INDEX_PATH, lines.join('\n') + '\n');
  console.log(`  ✓ Wrote ${relative(PATHS.root, INDEX_PATH)} (${all.length} entries)`);
  if (unknownTags.size > 0) {
    console.warn(`  ⚠ ${unknownTags.size} unknown tag(s). See INDEX.md for details.`);
  }
}

main();
